apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default-gcp
spec:
  projectID: <Project ID>              # Change the project id
  credentials:
  credentials:
    impersonateServiceAccount:
      name: ""
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-secret
      key: creds
